git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-
  branch: release4.3
  maintainers:
    - '0064428F455451B3EBE78A7F063938BA42CFA724'
    - '274E12AB03F2FE293765FC06DA0434BC706E1FCF'

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.3

distributions:
  - host-fcrq

components:
  - builder-rpm:
      packages: False
      branch: main
  - linux-utils
  - dracut
  - linux-kernel-latest:
      url: https://github.com/dill-shower/qubes-linux-kernel
      branch: main
      timeout: 21600
      host-fc41:
        stages:
          - build:
              environment:
                MAKEFLAGS: "-j$(($(nproc) * 2))"

executor:
  type: docker
  options:
    image: "qubes-builder-fedora:latest"
    clean: True
    cpus: "0.000" 

stages:
  - fetch
  - prep
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
