git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-
  branch: release4.2
  maintainers:
    # marmarek
    - '0064428F455451B3EBE78A7F063938BA42CFA724'
    # simon
    - '274E12AB03F2FE293765FC06DA0434BC706E1FCF'
  # Глобальное отключение проверки подписи
  insecure-skip-checking: true

backend-vmm: xen
debug: false
verbose: true
qubes-release: r4.2

# Добавляем оптимизацию и архитектуру
target-architecture: x86_64-v3
compiler-optimization: O3

# Оставляем только одну distribution для сборки
distributions:
  - host-fc37

# Убираем templates, так как они не нужны для сборки ядра
components:
  - builder-rpm:
      packages: False
      branch: main
  - linux-utils  # Нужно для установки ядра
  - dracut       # Для создания initramfs
  - linux-kernel:
      # Меняем URL репозитория и ветку
      url: https://github.com/dill-shower/qubes-linux-kernel
      branch: main
      timeout: 21600
      build-options:
        architecture: x86_64-v3
        optimization: O3
      # Дополнительно указываем отключение проверки для компонента
      fetch-options:
        insecure-skip-checking: true

# Используем Docker вместо dispvm
executor:
  type: docker
  options:
    image: "qubes-builder-fedora:latest"
    docker-opts: "-v /root/rpm:/builder/repository"

stages:
  - fetch
  - prep
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
  - upload:
      executor:
        type: local
